server:
  port: 8082

spring:
  application:
    name: appointments-service

  datasource:
    # Ajustado al puerto estándar 5432, usuario postgres y tu contraseña unificada
    url: jdbc:postgresql://localhost:5432/appointments_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Cambiado a true para que veas las consultas en consola mientras depuras
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
        default-requeue-rejected: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.medical: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG # Cambiado a DEBUG para ver el mapeo de tablas de citas
    org.springframework.amqp: INFO